# Generated by Django 4.0 on 2024-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('intention', models.TextField()),
                ('demandeur', models.TextField()),
                ('Uid', models.CharField(max_length=100)),
            ],
        ),
    ]
