# Generated by Django 4.0 on 2024-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messe',
            name='Uid',
        ),
        migrations.AlterField(
            model_name='messe',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messe',
            name='heure',
            field=models.CharField(max_length=60),
        ),
    ]
