# Generated by Django 4.0 on 2024-06-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messe', '0002_remove_messe_uid_alter_messe_date_alter_messe_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='messe',
            name='Uid',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
