# Generated by Django 5.0.6 on 2024-07-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messe', '0004_messe_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messe',
            name='transaction_id',
        ),
    ]
